name: quote_generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.7
      - run: go install
      - name: Generate quote
        run: github-profile
      - name: Update README.md
        run: |
          git config --global user.email "hungthai1401.it@gmail.com"
          git config --global user.name "Thai Nguyen Hung"
          git add .
          git commit -m "Updated README.md" || echo "No changes to commit"
          git push
